/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cw.pos1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author King
 */
public class AllCustomers extends javax.swing.JFrame {

    /**
     * Creates new form AllCustomers
     */
    public AllCustomers() {
        initComponents();
        setLocationRelativeTo(this);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        pnlAllCust = new javax.swing.JPanel();
        btnBack1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAllCust = new javax.swing.JTable();

        jLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 0, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("All Customers");

        pnlAllCust.setBackground(new java.awt.Color(204, 255, 255));

        btnBack1.setBackground(new java.awt.Color(255, 51, 51));
        btnBack1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        tblAllCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "XS", "S", "M", "L", "XL", "XXL", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAllCust);
        if (tblAllCust.getColumnModel().getColumnCount() > 0) {
            tblAllCust.getColumnModel().getColumn(0).setResizable(false);
            tblAllCust.getColumnModel().getColumn(1).setResizable(false);
            tblAllCust.getColumnModel().getColumn(2).setResizable(false);
            tblAllCust.getColumnModel().getColumn(3).setResizable(false);
            tblAllCust.getColumnModel().getColumn(4).setResizable(false);
            tblAllCust.getColumnModel().getColumn(5).setResizable(false);
            tblAllCust.getColumnModel().getColumn(6).setResizable(false);
            tblAllCust.getColumnModel().getColumn(7).setResizable(false);
        }

        javax.swing.GroupLayout pnlAllCustLayout = new javax.swing.GroupLayout(pnlAllCust);
        pnlAllCust.setLayout(pnlAllCustLayout);
        pnlAllCustLayout.setHorizontalGroup(
            pnlAllCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllCustLayout.createSequentialGroup()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAllCustLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        pnlAllCustLayout.setVerticalGroup(
            pnlAllCustLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAllCustLayout.createSequentialGroup()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAllCust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAllCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        ViewReports rep = new ViewReports();
        rep.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlAllCust;
    private javax.swing.JTable tblAllCust;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
         if (mainMenu.OrderList.size() > 0) {
                String[] allCust = new String[0];
                L1:
                for (int i = 0; i < mainMenu.OrderList.size(); i++) {
                    Order ord = mainMenu.OrderList.get(i);
                    for (int j = 0; j < allCust.length; j++) {
                        if (allCust[j].equals(ord.getPnum())) {
                            continue L1;
                        }
                    }
                    allCust = BestInCustomers.extendSingleStringArray(allCust);
                    allCust[allCust.length - 1] = ord.getPnum();
                }

                DefaultTableModel dtm =(DefaultTableModel)tblAllCust.getModel();
                dtm.setRowCount(0);
                DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
                dtcr.setHorizontalAlignment(jLabel.CENTER);
                
                tblAllCust.getColumnModel().getColumn(0).setCellRenderer(dtcr);
                tblAllCust.getColumnModel().getColumn(1).setCellRenderer(dtcr);
                tblAllCust.getColumnModel().getColumn(2).setCellRenderer(dtcr);
                tblAllCust.getColumnModel().getColumn(3).setCellRenderer(dtcr);
                tblAllCust.getColumnModel().getColumn(4).setCellRenderer(dtcr);
                tblAllCust.getColumnModel().getColumn(5).setCellRenderer(dtcr);
                tblAllCust.getColumnModel().getColumn(6).setCellRenderer(dtcr);
                tblAllCust.getColumnModel().getColumn(7).setCellRenderer(dtcr);
                for (int i = 0; i < allCust.length; i++) {
                    int[] items = new int[6];

                    for (int j = 0; j < mainMenu.OrderList.size(); j++) {
                        Order ord = mainMenu.OrderList.get(j);
                        if (allCust[i].equals(ord.getPnum())) {
                            switch (ord.getSize()) {
                                case "XS":
                                    items[0] += ord.getQty();
                                    break;
                                case "S":
                                    items[1] += ord.getQty();
                                    break;
                                case "M":
                                    items[2] += ord.getQty();
                                    break;
                                case "L":
                                    items[3] += ord.getQty();
                                    break;
                                case "XL":
                                    items[4] += ord.getQty();
                                    break;
                                case "XXL":
                                    items[5] += ord.getQty();
                                    break;
                            }
                        }
                    }
                    double totPrice = 0;

                    totPrice += (items[0] * PlaceOrder.prices[0]);
                    totPrice += (items[1] * PlaceOrder.prices[1]);
                    totPrice += (items[2] * PlaceOrder.prices[2]);
                    totPrice += (items[3] * PlaceOrder.prices[3]);
                    totPrice += (items[4] * PlaceOrder.prices[4]);
                    totPrice += (items[5] * PlaceOrder.prices[5]);

                    dtm.addRow(new String[]{allCust[i],String.valueOf(items[0]), String.valueOf(items[1]), String.valueOf(items[2]) ,String.valueOf(items[3]) , String.valueOf(items[4]) , String.valueOf(items[5]) , String.format("%.2f", totPrice) });
              
                }
            } else {
                JOptionPane.showMessageDialog(this, "Information not Found...");
            }

    }
}
