/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cw.pos1;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author King
 */
public class BestInCustomers extends javax.swing.JFrame {

    /**
     * Creates new form BestInCustomers
     */
    public BestInCustomers() {
        initComponents();
        setLocationRelativeTo(null);
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBIC = new javax.swing.JPanel();
        btnBack1 = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBIC = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Best In Customer");

        pnlBIC.setBackground(new java.awt.Color(204, 255, 255));

        btnBack1.setBackground(new java.awt.Color(255, 51, 51));
        btnBack1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(255, 255, 255));
        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 0, 0));

        tblBIC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "QTY", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBIC.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblBIC);
        if (tblBIC.getColumnModel().getColumnCount() > 0) {
            tblBIC.getColumnModel().getColumn(0).setResizable(false);
            tblBIC.getColumnModel().getColumn(1).setResizable(false);
            tblBIC.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout pnlBICLayout = new javax.swing.GroupLayout(pnlBIC);
        pnlBIC.setLayout(pnlBICLayout);
        pnlBICLayout.setHorizontalGroup(
            pnlBICLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBICLayout.createSequentialGroup()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlBICLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBICLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        pnlBICLayout.setVerticalGroup(
            pnlBICLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBICLayout.createSequentialGroup()
                .addComponent(btnBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBIC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBIC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        ViewReports rep = new ViewReports();
        rep.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBack1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BestInCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BestInCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BestInCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BestInCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BestInCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlBIC;
    private javax.swing.JTable tblBIC;
    // End of variables declaration//GEN-END:variables

    public static String[] extendSingleStringArray(String[] ar) {
        String[] tempAr = new String[ar.length + 1];
        for (int i = 0; i < ar.length; i++) {
            tempAr[i] = ar[i];
        }
        return tempAr;
    }    
    
    private void loadData() {
        
        int inKey;
        
            if (mainMenu.OrderList.size() > 0) {
                String[] bestInCust = new String[0];
                L1:
                for (int i = 0; i < mainMenu.OrderList.size(); i++) {
                    Order ord = mainMenu.OrderList.get(i);
                    for (int j = 0; j < bestInCust.length; j++) {
                        if (bestInCust[j].equals(ord.getPnum())) {
                            continue L1;
                        }
                    }
                    bestInCust = extendSingleStringArray(bestInCust);
                    bestInCust[bestInCust.length - 1] = ord.getPnum();
                }
                int[] sumOfQty = new int[bestInCust.length];
                double[] sumOfAmount = new double[bestInCust.length];

                for (int i = 0; i < bestInCust.length; i++) {

                    int totalQty = 0;
                    double totalAmount = 0;
                    for (int j = 0; j < mainMenu.OrderList.size(); j++) {
                        Order ord = mainMenu.OrderList.get(j);
                        if (bestInCust[i].equals(ord.getPnum())) {
                            totalQty += ord.getQty();
                            totalAmount += ord.getTamount();
                        }
                    }

                    sumOfQty[i] = totalQty;
                    sumOfAmount[i] = totalAmount;

                }

                for (int j = 0; j < bestInCust.length; j++) {
                    for (int i = 0; i < bestInCust.length - 1; i++) {
                        if (sumOfAmount[i + 1] > sumOfAmount[i]) {
                            double totalAmount = sumOfAmount[i];
                            sumOfAmount[i] = sumOfAmount[i + 1];
                            sumOfAmount[i + 1] = totalAmount;

                            String bestCust = bestInCust[i];
                            bestInCust[i] = bestInCust[i + 1];
                            bestInCust[i + 1] = bestCust;

                            int allQty = sumOfQty[i];
                            sumOfQty[i] = sumOfQty[i + 1];
                            sumOfQty[i + 1] = allQty;

                        }
                    }
                }
                
                
                DefaultTableModel dtm =(DefaultTableModel)tblBIC.getModel();
                dtm.setRowCount(0);
                DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
                dtcr.setHorizontalAlignment(jLabel.CENTER);
                
                tblBIC.getColumnModel().getColumn(0).setCellRenderer(dtcr);
                tblBIC.getColumnModel().getColumn(1).setCellRenderer(dtcr);
                tblBIC.getColumnModel().getColumn(2).setCellRenderer(dtcr);
                
                for (int i = 0; i < bestInCust.length; i++) {
                    dtm.addRow(new String[]{bestInCust[i],String.valueOf(sumOfQty[i]),String.format("%.2f",sumOfAmount[i])} );
                }

            } else {
                JOptionPane.showMessageDialog(this, "Information not Found...");
                //this.dispose();
            }
            
    }
}
