/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cw.pos1;

import javax.swing.JOptionPane;

/**
 *
 * @author King
 */
public class Delete extends javax.swing.JFrame {

    /**
     * Creates new form Delete
     */
    public Delete() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSO = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        lblEOI2 = new javax.swing.JLabel();
        txtEOI2 = new javax.swing.JTextField();
        btnSearchOid2 = new javax.swing.JButton();
        lblCustId2 = new javax.swing.JLabel();
        lblSize2 = new javax.swing.JLabel();
        lblQty2 = new javax.swing.JLabel();
        lblAmount2 = new javax.swing.JLabel();
        lblStatus2 = new javax.swing.JLabel();
        lblCIdFill2 = new javax.swing.JLabel();
        lblSfill2 = new javax.swing.JLabel();
        lblQfill2 = new javax.swing.JLabel();
        lblAfill2 = new javax.swing.JLabel();
        lblStatFill2 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete");

        pnlSO.setBackground(new java.awt.Color(204, 255, 255));

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 0, 0));

        lblEOI2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEOI2.setText("Enter Order ID : ");

        txtEOI2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSearchOid2.setBackground(new java.awt.Color(0, 204, 204));
        btnSearchOid2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSearchOid2.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchOid2.setText("Search");
        btnSearchOid2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchOid2ActionPerformed(evt);
            }
        });

        lblCustId2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustId2.setText("Customer ID : ");

        lblSize2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSize2.setText("Size :");

        lblQty2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQty2.setText("QTY :");

        lblAmount2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAmount2.setText("Amount :");

        lblStatus2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatus2.setText("Status :");

        lblCIdFill2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblSfill2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblQfill2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblAfill2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblStatFill2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnDelete.setBackground(new java.awt.Color(153, 0, 0));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSOLayout = new javax.swing.GroupLayout(pnlSO);
        pnlSO.setLayout(pnlSOLayout);
        pnlSOLayout.setHorizontalGroup(
            pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSOLayout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlSOLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSOLayout.createSequentialGroup()
                        .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustId2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSize2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQty2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCIdFill2, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(lblSfill2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQfill2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAfill2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatFill2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlSOLayout.createSequentialGroup()
                        .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSOLayout.createSequentialGroup()
                                .addComponent(lblEOI2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEOI2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlSOLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearchOid2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        pnlSOLayout.setVerticalGroup(
            pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSOLayout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSOLayout.createSequentialGroup()
                        .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearchOid2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEOI2)
                            .addComponent(lblEOI2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addComponent(lblCustId2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSize2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQty2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSOLayout.createSequentialGroup()
                        .addComponent(lblCIdFill2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSfill2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQfill2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAfill2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatFill2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSOLayout.createSequentialGroup()
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSOLayout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainMenu menu = new mainMenu();
        menu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchOid2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchOid2ActionPerformed
        lblCIdFill2.setText("");
        lblSfill2.setText("");
        lblQfill2.setText("");
        lblAfill2.setText("");
        lblStatFill2.setText("");

        String oid=txtEOI2.getText().toUpperCase();
        boolean id = false;
        for (int i = 0; i < mainMenu.OrderList.size(); i++) {
            Order ord = mainMenu.OrderList.get(i);
            if (ord.getOrderId().equals(oid)) {

                lblCIdFill2.setText(ord.getOrderId());
                lblSfill2.setText(ord.getSize());
                lblQfill2.setText(String.valueOf(ord.getQty()));
                lblAfill2.setText(String.valueOf(ord.getTamount()));
                lblStatFill2.setText(ord.getSavestat());

                id = true;
                break;
            }
        }

        if (!id) {
            JOptionPane.showMessageDialog(this, "Order ID not Found...");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchOid2ActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
               lblCIdFill2.setText("");
        lblSfill2.setText("");
        lblQfill2.setText("");
        lblAfill2.setText("");
        lblStatFill2.setText("");

        String oid=txtEOI2.getText().toUpperCase();
        boolean id = false;
        for (int i = 0; i < mainMenu.OrderList.size(); i++) {
            Order ord = mainMenu.OrderList.get(i);
            if (ord.getOrderId().equals(oid)) {

                lblCIdFill2.setText(ord.getOrderId());
                lblSfill2.setText(ord.getSize());
                lblQfill2.setText(String.valueOf(ord.getQty()));
                lblAfill2.setText(String.valueOf(ord.getTamount()));
                lblStatFill2.setText(ord.getSavestat());
                String[] options = {"Yes", "No"};
                     int choice = JOptionPane.showOptionDialog(this, "Do You Want to Dekete this Order...", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
                     
                if (choice==0) {
                
                mainMenu.OrderList.remove(i);
                JOptionPane.showMessageDialog(this, "Order Deleted...");
                    
                }
                id = true;
                break;
            }
        }

        if (!id) {
            JOptionPane.showMessageDialog(this, "Order ID not Found...");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearchOid2;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel lblAfill2;
    private javax.swing.JLabel lblAmount2;
    private javax.swing.JLabel lblCIdFill2;
    private javax.swing.JLabel lblCustId2;
    private javax.swing.JLabel lblEOI2;
    private javax.swing.JLabel lblQfill2;
    private javax.swing.JLabel lblQty2;
    private javax.swing.JLabel lblSfill2;
    private javax.swing.JLabel lblSize2;
    private javax.swing.JLabel lblStatFill2;
    private javax.swing.JLabel lblStatus2;
    private javax.swing.JPanel pnlSO;
    private javax.swing.JTextField txtEOI2;
    // End of variables declaration//GEN-END:variables
}
