/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cw.pos1;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author King
 */
public class SearchCustomer extends javax.swing.JFrame {

    /**
     * Creates new form SearchCustomer
     */
    public SearchCustomer() {
        initComponents();
        setLocationRelativeTo(this);
        
        //loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSC = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblECI = new javax.swing.JLabel();
        txtSECI = new javax.swing.JTextField();
        btnSearchCid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSerCust = new javax.swing.JTable();
        lblTotFill = new javax.swing.JLabel();
        lblTot = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Customer");

        pnlSC.setBackground(new java.awt.Color(204, 255, 255));

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblECI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblECI.setText("Enter Customer ID : ");

        txtSECI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSearchCid.setBackground(new java.awt.Color(0, 204, 204));
        btnSearchCid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSearchCid.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchCid.setText("Search");
        btnSearchCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchCidActionPerformed(evt);
            }
        });

        tblSerCust.setAutoCreateRowSorter(true);
        tblSerCust.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblSerCust.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Size", "QTY", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSerCust.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblSerCust.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblSerCust);
        if (tblSerCust.getColumnModel().getColumnCount() > 0) {
            tblSerCust.getColumnModel().getColumn(0).setResizable(false);
            tblSerCust.getColumnModel().getColumn(1).setResizable(false);
            tblSerCust.getColumnModel().getColumn(2).setResizable(false);
        }

        lblTotFill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotFill.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lblTot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTot.setText("Total : ");

        javax.swing.GroupLayout pnlSCLayout = new javax.swing.GroupLayout(pnlSC);
        pnlSC.setLayout(pnlSCLayout);
        pnlSCLayout.setHorizontalGroup(
            pnlSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSCLayout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlSCLayout.createSequentialGroup()
                .addGroup(pnlSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSCLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblECI, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSECI, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnSearchCid, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSCLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(pnlSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotFill, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(pnlSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlSCLayout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(lblTot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(441, Short.MAX_VALUE)))
        );
        pnlSCLayout.setVerticalGroup(
            pnlSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSCLayout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearchCid, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(txtSECI)
                    .addComponent(lblECI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(lblTotFill, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(pnlSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSCLayout.createSequentialGroup()
                    .addContainerGap(480, Short.MAX_VALUE)
                    .addComponent(lblTot, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(73, 73, 73)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainMenu menu = new mainMenu();
        menu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchCidActionPerformed
        String phone=txtSECI.getText();
        int i;
        int xsCount = 0;
        int sCount = 0;
        int mCount = 0;
        int lCount = 0;
        int xlCount = 0;
        int xxlCount = 0;

        double xsAmount = 0;
        double sAmount = 0;
        double mAmount = 0;
        double lAmount = 0;
        double xlAmount = 0;
        double xxlAmount = 0;

        Order order = new Order(null, phone, null, 0, null, 0);
        int index = mainMenu.OrderList.indexOf(order);
        if(mainMenu.OrderList.size()>0){
            for (i = 0; i < mainMenu.OrderList.size(); i++) {
                Order ord = mainMenu.OrderList.get(i);
                if (ord.getPnum().equalsIgnoreCase(phone)) {

                    switch (mainMenu.OrderList.get(i).getSize()) {
                        case "XS":
                        xsCount += ord.getQty();
                        xsAmount += ord.getTamount();
                        break;

                        case "S":
                        sCount += ord.getQty();
                        sAmount += ord.getTamount();
                        break;

                        case "M":
                        mCount += ord.getQty();
                        mAmount += ord.getTamount();
                        break;

                        case "L":
                        lCount += ord.getQty();
                        lAmount += ord.getTamount();
                        break;

                        case "XL":
                        xlCount += ord.getQty();
                        xlAmount += ord.getTamount();
                        break;

                        case "XXL":
                        xxlCount += ord.getQty();
                        xxlAmount += ord.getTamount();
                        break;
                    }

                    String XS[]={"XS",String.valueOf(xsCount),String.valueOf(xsAmount)};
                    String S[]={"S",String.valueOf(sCount),String.valueOf(sAmount)};
                    String M[]={"M",String.valueOf(mCount),String.valueOf(mAmount)};
                    String L[]={"L",String.valueOf(lCount),String.valueOf(lAmount)};
                    String XL[]={"XL",String.valueOf(xlCount),String.valueOf(xlAmount)};
                    String XXL[]={"XXL",String.valueOf(xxlCount),String.valueOf(xxlAmount)};

                    DefaultTableModel dtm =(DefaultTableModel)tblSerCust.getModel();
                    dtm.setRowCount(0);
                    DefaultTableCellRenderer dtcr = new DefaultTableCellRenderer();
                    dtcr.setHorizontalAlignment(JLabel.CENTER);
                    tblSerCust.getColumnModel().getColumn(0).setCellRenderer(dtcr);
                    tblSerCust.getColumnModel().getColumn(1).setCellRenderer(dtcr);
                    tblSerCust.getColumnModel().getColumn(2).setCellRenderer(dtcr);
                    
                    
                    dtm.setRowCount(0);
                    dtm.addRow(XS);
                    dtm.addRow(S);
                    dtm.addRow(M);
                    dtm.addRow(L);
                    dtm.addRow(XL);
                    dtm.addRow(XXL);
                    
                    lblTotFill.setText(String.format("%.2f",xsAmount+sAmount+mAmount+lAmount+xlAmount+xxlAmount ));
                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "Customer ID not Found...");
                    break;
                }

            }
        }else if(mainMenu.OrderList.size()<=0){
            JOptionPane.showMessageDialog(this, "Customer ID not Found...");
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchCidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearchCid;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblECI;
    private javax.swing.JLabel lblTot;
    private javax.swing.JLabel lblTotFill;
    private javax.swing.JPanel pnlSC;
    private javax.swing.JTable tblSerCust;
    private javax.swing.JTextField txtSECI;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        DefaultTableModel dtm =(DefaultTableModel)tblSerCust.getModel();
        dtm.setRowCount(0);
    }
}
