/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cw.pos1;

import javax.swing.JOptionPane;

/**
 *
 * @author King
 */
public class Status extends javax.swing.JFrame {

    /**
     * Creates new form Status
     */
    public Status() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSO = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        lblEOI = new javax.swing.JLabel();
        txtEOI = new javax.swing.JTextField();
        btnSearchOid = new javax.swing.JButton();
        lblCustId = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        lblQty = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblCIdFill = new javax.swing.JLabel();
        lblSfill = new javax.swing.JLabel();
        lblQfill = new javax.swing.JLabel();
        lblAfill = new javax.swing.JLabel();
        lblStatFill = new javax.swing.JLabel();
        btnStatChg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Status");

        pnlSO.setBackground(new java.awt.Color(204, 255, 255));

        btnBack.setBackground(new java.awt.Color(255, 51, 51));
        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 0, 0));

        lblEOI.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEOI.setText("Enter Order ID : ");

        txtEOI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSearchOid.setBackground(new java.awt.Color(0, 204, 204));
        btnSearchOid.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSearchOid.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchOid.setText("Search");
        btnSearchOid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchOidActionPerformed(evt);
            }
        });

        lblCustId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCustId.setText("Customer ID : ");

        lblSize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSize.setText("Size :");

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblQty.setText("QTY :");

        lblAmount.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAmount.setText("Amount :");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblStatus.setText("Status :");

        lblCIdFill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblSfill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblQfill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblAfill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblStatFill.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        btnStatChg.setBackground(new java.awt.Color(0, 51, 204));
        btnStatChg.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnStatChg.setForeground(new java.awt.Color(255, 255, 255));
        btnStatChg.setText("Change Status");
        btnStatChg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatChgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSOLayout = new javax.swing.GroupLayout(pnlSO);
        pnlSO.setLayout(pnlSOLayout);
        pnlSOLayout.setHorizontalGroup(
            pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSOLayout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlSOLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSOLayout.createSequentialGroup()
                        .addComponent(lblEOI, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEOI, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnSearchOid, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSOLayout.createSequentialGroup()
                        .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCIdFill, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(lblSfill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblQfill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAfill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatFill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlSOLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnStatChg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        pnlSOLayout.setVerticalGroup(
            pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSOLayout.createSequentialGroup()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSOLayout.createSequentialGroup()
                        .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSearchOid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEOI)
                            .addComponent(lblEOI, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addComponent(lblCustId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSOLayout.createSequentialGroup()
                        .addComponent(lblCIdFill, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblSfill, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblQfill, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAfill, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatFill, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStatChg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static final String[] stat = {"Processing", "Delivering", "Delivered"};
        
        
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        mainMenu menu = new mainMenu();
        menu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchOidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchOidActionPerformed
        lblCIdFill.setText("");
        lblSfill.setText("");
        lblQfill.setText("");
        lblAfill.setText("");
        lblStatFill.setText("");

        String oid=txtEOI.getText().toUpperCase();
        boolean id = false;
        for (int i = 0; i < mainMenu.OrderList.size(); i++) {
            Order ord = mainMenu.OrderList.get(i);
            if (ord.getOrderId().equals(oid)) {

                lblCIdFill.setText(ord.getOrderId());
                lblSfill.setText(ord.getSize());
                lblQfill.setText(String.valueOf(ord.getQty()));
                lblAfill.setText(String.valueOf(ord.getTamount()));
                lblStatFill.setText(ord.getSavestat());
                
                
                id = true;
                break;
            }
        }

        if (!id) {
            JOptionPane.showMessageDialog(this, "Order ID not Found...");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchOidActionPerformed

    private void btnStatChgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatChgActionPerformed
        lblCIdFill.setText("");
        lblSfill.setText("");
        lblQfill.setText("");
        lblAfill.setText("");
        lblStatFill.setText("");

        String oid=txtEOI.getText().toUpperCase();
        boolean id = false;
        for (int i = 0; i < mainMenu.OrderList.size(); i++) {
            Order ord = mainMenu.OrderList.get(i);
            if (ord.getOrderId().equals(oid)) {

                lblCIdFill.setText(ord.getOrderId());
                lblSfill.setText(ord.getSize());
                lblQfill.setText(String.valueOf(ord.getQty()));
                lblAfill.setText(String.valueOf(ord.getTamount()));
                lblStatFill.setText(ord.getSavestat());

                
                if (ord.getSavestat().equals(PlaceOrder.stat[0])) {
                     String[] options = {"Delivering", "Delivered"};
                     int choice = JOptionPane.showOptionDialog(this, "Please Select the Status...", "Status", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
                     switch (choice) {
                        case 0 -> {
                            ord.setSavestat(stat[1]);
                            JOptionPane.showMessageDialog(this, "Status Updated...");
                        }
                        case 1 -> {
                            ord.setSavestat(stat[2]);
                            JOptionPane.showMessageDialog(this, "Status Updated...");
                        }
                    }
                }else if (ord.getSavestat().equals(PlaceOrder.stat[1])) {
                     Object[] options = {"Delivered"};
                     int choice = JOptionPane.showOptionDialog(this, "Please Select the Status...", "Status", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
                     if (choice==0) {
                        ord.setSavestat(stat[2]);
                            JOptionPane.showMessageDialog(this, "Status Updated...");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Can't change this order status, Orders already delivered..!");
                }
                
                id = true;
                break;
            }
        }

        if (!id) {
            JOptionPane.showMessageDialog(this, "Order ID not Found...");
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_btnStatChgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearchOid;
    private javax.swing.JButton btnStatChg;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel lblAfill;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCIdFill;
    private javax.swing.JLabel lblCustId;
    private javax.swing.JLabel lblEOI;
    private javax.swing.JLabel lblQfill;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblSfill;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblStatFill;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPanel pnlSO;
    private javax.swing.JTextField txtEOI;
    // End of variables declaration//GEN-END:variables
}
