/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cw.pos1;

/**
 *
 * @author King
 */
public class ViewReports extends javax.swing.JFrame {

    /**
     * Creates new form ViewReports
     */
    public ViewReports() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVR = new javax.swing.JPanel();
        btnBack2 = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        btnVcust = new javax.swing.JButton();
        btnBinC = new javax.swing.JButton();
        btnAllCust = new javax.swing.JButton();
        btnCBqty = new javax.swing.JButton();
        btnCBamo = new javax.swing.JButton();
        btnOBamo = new javax.swing.JButton();
        btnAllOrds = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Reports");

        pnlVR.setBackground(new java.awt.Color(204, 255, 255));

        btnBack2.setBackground(new java.awt.Color(255, 51, 51));
        btnBack2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(255, 255, 255));
        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        jLabel.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 0, 0));

        btnVcust.setBackground(new java.awt.Color(0, 204, 0));
        btnVcust.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnVcust.setForeground(new java.awt.Color(255, 255, 255));
        btnVcust.setText("View Customers");
        btnVcust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVcustActionPerformed(evt);
            }
        });

        btnBinC.setBackground(new java.awt.Color(0, 204, 0));
        btnBinC.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnBinC.setForeground(new java.awt.Color(255, 255, 255));
        btnBinC.setText("Best In Customers");
        btnBinC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBinCActionPerformed(evt);
            }
        });

        btnAllCust.setBackground(new java.awt.Color(0, 204, 0));
        btnAllCust.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAllCust.setForeground(new java.awt.Color(255, 255, 255));
        btnAllCust.setText("All Customers");
        btnAllCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllCustActionPerformed(evt);
            }
        });

        btnCBqty.setBackground(new java.awt.Color(0, 51, 204));
        btnCBqty.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCBqty.setForeground(new java.awt.Color(255, 255, 255));
        btnCBqty.setText("Categorized By QTY ");
        btnCBqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCBqtyActionPerformed(evt);
            }
        });

        btnCBamo.setBackground(new java.awt.Color(0, 51, 204));
        btnCBamo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnCBamo.setForeground(new java.awt.Color(255, 255, 255));
        btnCBamo.setText("Categorized By Amount");
        btnCBamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCBamoActionPerformed(evt);
            }
        });

        btnOBamo.setBackground(new java.awt.Color(102, 102, 102));
        btnOBamo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnOBamo.setForeground(new java.awt.Color(255, 255, 255));
        btnOBamo.setText("Orders By Amount");
        btnOBamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOBamoActionPerformed(evt);
            }
        });

        btnAllOrds.setBackground(new java.awt.Color(102, 102, 102));
        btnAllOrds.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnAllOrds.setForeground(new java.awt.Color(255, 255, 255));
        btnAllOrds.setText("All Orders");
        btnAllOrds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllOrdsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVRLayout = new javax.swing.GroupLayout(pnlVR);
        pnlVR.setLayout(pnlVRLayout);
        pnlVRLayout.setHorizontalGroup(
            pnlVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVRLayout.createSequentialGroup()
                .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlVRLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBinC, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(btnVcust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAllCust, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(pnlVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCBqty, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCBamo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(pnlVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVRLayout.createSequentialGroup()
                        .addComponent(btnAllOrds, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnOBamo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlVRLayout.setVerticalGroup(
            pnlVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVRLayout.createSequentialGroup()
                .addComponent(btnBack2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlVRLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnVcust, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlVRLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(pnlVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOBamo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCBqty, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnlVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVRLayout.createSequentialGroup()
                        .addComponent(btnBinC, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnAllCust, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(pnlVRLayout.createSequentialGroup()
                        .addGroup(pnlVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlVRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnCBamo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAllOrds, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVR, javax.swing.GroupLayout.PREFERRED_SIZE, 821, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlVR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        mainMenu menu = new mainMenu();
        menu.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void btnCBqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCBqtyActionPerformed
        CategarizedByQTY rep=new CategarizedByQTY();
        rep.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCBqtyActionPerformed

    private void btnCBamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCBamoActionPerformed
        CategarizedByAmount rep=new CategarizedByAmount();
        rep.setVisible(true);       
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnCBamoActionPerformed

    private void btnBinCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBinCActionPerformed
        BestInCustomers rep =new BestInCustomers();
        rep.setVisible(true); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBinCActionPerformed

    private void btnVcustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVcustActionPerformed
        ViewCustomers rep=new ViewCustomers();
        rep.setVisible(true);  
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnVcustActionPerformed

    private void btnAllCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllCustActionPerformed
        AllCustomers rep=new AllCustomers();
        rep.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnAllCustActionPerformed

    private void btnOBamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOBamoActionPerformed
        OrdersByAmount rep=new OrdersByAmount();
        rep.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnOBamoActionPerformed

    private void btnAllOrdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllOrdsActionPerformed
        AllOrders rep= new AllOrders();
        rep.setVisible(true);
        this.dispose();
                // TODO add your handling code here:
    }//GEN-LAST:event_btnAllOrdsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllCust;
    private javax.swing.JButton btnAllOrds;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnBinC;
    private javax.swing.JButton btnCBamo;
    private javax.swing.JButton btnCBqty;
    private javax.swing.JButton btnOBamo;
    private javax.swing.JButton btnVcust;
    private javax.swing.JLabel jLabel;
    private javax.swing.JPanel pnlPO;
    private javax.swing.JPanel pnlPO1;
    private javax.swing.JPanel pnlVR;
    // End of variables declaration//GEN-END:variables
}
